config/routes.rb
Rails.application.routes.draw do
  resources :artist_profiles, except: [ :index ]
  resources :artist_portfolios, except: [ :index ]
  resources :artworks
  resources :artists
  resources :about, only: [ :index ]
  devise_for :users do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  namespace :admin do
    resources :dashboard
  end
  get "404" => "errors#not_found", as: :not_found
  # get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/artist_portfolio.rb
class ArtistPortfolio < ApplicationRecord
  has_one_attached :image
  belongs_to :artist
  belongs_to :user
  has_many :artworks
end

app/controllers/artist_portfolios_controller.rb
class ArtistPortfoliosController < ApplicationController
  before_action :set_artist_portfolio, only: %i[ show edit update destroy ]
  before_action :check_if_admin, only: [ :edit, :destroy, :new, :create, :update, :destroy ]
  skip_before_action :authenticate_user!

  # GET /artist_portfolios or /artist_portfolios.json
  def index
    @artist_portfolios = ArtistPortfolio.all
  end

  # GET /artist_portfolios/1 or /artist_portfolios/1.json
  def show
  end

  # GET /artist_portfolios/new
  def new
    @artist_portfolio = ArtistPortfolio.new
  end

  # GET /artist_portfolios/1/edit
  def edit
  end

  # POST /artist_portfolios or /artist_portfolios.json
  def create
    @artist_portfolio = ArtistPortfolio.new(artist_portfolio_params)

    respond_to do |format|
      if @artist_portfolio.save
        format.html { redirect_to @artist_portfolio, notice: "Artist portfolio was successfully created." }
        format.json { render :show, status: :created, location: @artist_portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist_portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artist_portfolios/1 or /artist_portfolios/1.json
  def update
    respond_to do |format|
      if @artist_portfolio.update(artist_portfolio_params)
        format.html { redirect_to @artist_portfolio, notice: "Artist portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: @artist_portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist_portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artist_portfolios/1 or /artist_portfolios/1.json
  def destroy
    @artist_portfolio.destroy!

    respond_to do |format|
      format.html { redirect_to artist_portfolios_path, status: :see_other, notice: "Artist portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist_portfolio
      @artist_portfolio = ArtistPortfolio.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artist_portfolio_params
      params.expect(artist_portfolio: [ :name, :description, :artist_id ])
    end
end

app/helpers/artist_portfolios_helper.rb
module ArtistPortfoliosHelper
end

app/views/artist_portfolios/_artist_portfolio.html.erb
<div id="<%= dom_id artist_portfolio %>">
  <p>
    <strong>Name:</strong>
    <%= artist_portfolio.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= artist_portfolio.description %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= artist_portfolio.artist_id %>
  </p>

</div>

app/views/artist_portfolios/_form.html.erb
<%= form_with(model: artist_portfolio) do |form| %>
  <% if artist_portfolio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist_portfolio.errors.count, "error") %> prohibited this artist_portfolio from being saved:</h2>

      <ul>
        <% artist_portfolio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :artist_id, style: "display: block" %>
    <%= form.number_field :artist_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artist_portfolios/edit.html.erb
<% content_for :title, "Editing artist portfolio" %>

<h1>Editing artist portfolio</h1>

<%= render "form", artist_portfolio: @artist_portfolio %>

<br>

<div>
  <%= link_to "Show this artist portfolio", @artist_portfolio %> |
  <%= link_to "Back to artist portfolios", artist_portfolios_path %>
</div>

app/views/artist_portfolios/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Artist portfolios" %>

<h1>Artist portfolios</h1>

<div id="artist_portfolios">
  <% @artist_portfolios.each do |artist_portfolio| %>
    <%= render artist_portfolio %>
    <p>
      <%= link_to "Show this artist portfolio", artist_portfolio %>
    </p>
  <% end %>
</div>

<%= link_to "New artist portfolio", new_artist_portfolio_path %>

app/views/artist_portfolios/new.html.erb
<% content_for :title, "New artist portfolio" %>

<h1>New artist portfolio</h1>

<%= render "form", artist_portfolio: @artist_portfolio %>

<br>

<div>
  <%= link_to "Back to artist portfolios", artist_portfolios_path %>
</div>

app/views/artist_portfolios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist_portfolio %>

<div>
  <%= link_to "Edit this artist portfolio", edit_artist_portfolio_path(@artist_portfolio) %> |
  <%= link_to "Back to artist portfolios", artist_portfolios_path %>

  <%= button_to "Destroy this artist portfolio", @artist_portfolio, method: :delete %>
</div>