config/routes.rb
Rails.application.routes.draw do
  resources :artist_profiles, except: [ :index ]
  resources :artist_portfolios, except: [ :index ]
  resources :artworks
  resources :artists
  resources :about, only: [ :index ]
  devise_for :users do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  namespace :admin do
    resources :dashboard
  end
  get "404" => "errors#not_found", as: :not_found
  # get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user
  has_many :artworks
  has_one_attached :image
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_path, status: :see_other, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:bio, :image)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.textarea :bio %>
  </div>

  <div>
    <%= form.label :image, "Upload profile image:", style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<% content_for :title, "Editing artist" %>

<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Artists" %>

<h1>Artists</h1>

<div id="artists" style="display: flex;">
  <% @artists.each do |artist| %>
    <% user = artist.user %>
    <div class="card" style="width: 18rem; margin: 2rem">
      <img src="https://images.unsplash.com/photo-1673379324645-21a670fc74c8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZmlsZSUyMHBpYyUyMGljb258ZW58MHx8MHx8fDA%3D" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= artist.user.first_name + " " + artist.user.last_name%></h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card’s content.</p>
        <%= link_to "Show this artist", artist, class:"btn btn-secondary" %>
      </div>
    </div>
    <br>
  <% end %>
</div>
<% if current_user&.admin?%>
  <%= link_to "New artist", new_artist_path %>
<%end%>

app/views/artists/new.html.erb
<% content_for :title, "New artist" %>

<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
<style>
  body {
    min-height: 100vh;
    font: normal 16px sans-serif;
    padding: 40px 0;
  }

  .container.gallery-container {
      background-color: #fff;
      color: #35373a;
      min-height: 100vh;
      padding: 10px 20px;
  }

  .gallery-container h1 {
      text-align: center;
      margin-top: 50px;
      font-family: 'Droid Sans', sans-serif;
      font-weight: bold;
  }

  .gallery-container p.page-description {
      text-align: center;
      margin: 25px auto;
      font-size: 18px;
      color: #999;
  }

  .tz-gallery {
      padding: 40px;
  }

  /* Override bootstrap column paddings */
  .tz-gallery .row>div {
      padding: 2px;
  }

  .tz-gallery .lightbox img {
      width: 100%;
      border-radius: 0;
      position: relative;
  }

  .tz-gallery .lightbox:before {
      top: 50%;
      left: 50%;
      margin-top: -13px;
      margin-left: -13px;
      opacity: 0;
      color: #fff;
      font-size: 26px;
      font-family: 'Glyphicons Halflings';
      content: '\e003';
      pointer-events: none;
      z-index: 9000;
      transition: 0.4s;
  }


  .tz-gallery .lightbox:after {
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      opacity: 0;
      background-color: rgba(46, 132, 206, 0.7);
      content: '';
      transition: 0.4s;
  }

  .tz-gallery .lightbox:hover:after,
  .tz-gallery .lightbox:hover:before {
      opacity: 1;
  }

  .baguetteBox-button {
      background-color: transparent !important;
  }

  @media(max-width: 768px) {
      body {
          padding: 0;
      }
  }
</style>

<p style="color: green"><%= notice %></p>

<div class="container mt-1">
  <div class="row">
    <div class="col text-center">
      <div class="avatar mx-auto mb-3">
        <img src="https://images.unsplash.com/photo-1673379324645-21a670fc74c8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZmlsZSUyMHBpYyUyMGljb258ZW58MHx8MHx8fDA%3D" class="img-fluid" alt="User Avatar">
      </div>
      <h3><%= @artist.user.first_name + " " + @artist.user.last_name%></h3>
      <p>Email: <%= @artist.user.email%></p>
      <p><%= @artist.bio%></p>
    </div>
  </div>
</div>

<div class="container gallery-container">

    <h1><%= @artist.user.first_name + " " + @artist.user.last_name + "'s Gallery"%></h1>

      <p class="page-description text-center">Find all the beautiful artworks and pieces from <%= @artist.user.first_name + " " + @artist.user.last_name %></p>

    <div class="tz-gallery">
    <% if current_user %>
        <%= link_to "New artwork", new_artwork_path, class: "btn btn-outline-secondary" %>
    <% end %>
        <div class="row">
          <% @artist.artworks.each do |artwork| %>
            <% artwork.images.each do |image| %>
            <div class="col-sm-12 col-md-4">
              <%= link_to url_for(image), data: { lightbox: "artwork-group", title: artwork.description } do %>
                <%= image_tag url_for(image), alt: artwork.description, class: "img-thumbnail" %>
              <% end %>
            </div>
            <% end %>
          <% end %>
          </div>

    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>

<script>
    baguetteBox.run('.tz-gallery');
</script>
<br>

<div>
  <% if current_user == @artist.user%>
    <%= link_to "Edit", edit_artist_path(@artist), class:"btn btn-primary" %> |
  <% end %>  
  <%= link_to "Back to artists", artists_path, class: "btn btn-secondary" %>
  <% if current_user&.admin?%>
    <%= button_to "Destroy this artist", @artist, method: :delete %>
  <% end %>
</div>
<br>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>

<script>
    baguetteBox.run('.tz-gallery');
</script>