config/routes.rb
Rails.application.routes.draw do
  resources :artist_profiles, except: [ :index ]
  resources :artist_portfolios, except: [ :index ]
  resources :artworks
  resources :artists
  resources :about, only: [ :index ]
  devise_for :users do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  namespace :admin do
    resources :dashboard
  end
  get "404" => "errors#not_found", as: :not_found
  # get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_many_attached :images
  belongs_to :artist
  belongs_to :user
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  # GET /artworks or /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1 or /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks or /artworks.json
  def create
    user = current_user
    artist = user.artist

    @artwork = Artwork.new(artwork_params)
    @artwork.user = user
    @artwork.artist = artist

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: "Artwork was successfully created." }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1 or /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: "Artwork was successfully updated." }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1 or /artworks/1.json
  def destroy
    @artwork.destroy!

    respond_to do |format|
      format.html { redirect_to artworks_path, status: :see_other, notice: "Artwork was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.require(:artwork).permit(:name, :description, images: [])
    end

    def user
      current_user
    end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_artwork.html.erb
<div id="<%= dom_id artwork %>">
  <p>
    <strong>Name:</strong>
    <%= artwork.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= artwork.description %>
  </p>


</div>

app/views/artworks/_form.html.erb
<%= form_with(model: artwork) do |form| %>
  <% if artwork.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
        <% artwork.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :images, "Upload images:", style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<% content_for :title, "Editing artwork" %>

<h1>Editing artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Show this artwork", @artwork %> |
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/index.html.erb
<link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
<style>
  body {
    min-height: 100vh;
    font: normal 16px sans-serif;
    padding: 40px 0;
  }

  .container.gallery-container {
      background-color: #fff;
      color: #35373a;
      min-height: 100vh;
      padding: 10px 20px;
  }

  .gallery-container h1 {
      text-align: center;
      margin-top: 50px;
      font-family: 'Droid Sans', sans-serif;
      font-weight: bold;
  }

  .gallery-container p.page-description {
      text-align: center;
      margin: 25px auto;
      font-size: 18px;
      color: #999;
  }

  .tz-gallery {
      padding: 40px;
  }

  /* Override bootstrap column paddings */
  .tz-gallery .row>div {
      padding: 2px;
  }

  .tz-gallery .lightbox img {
      width: 100%;
      border-radius: 0;
      position: relative;
  }

  .tz-gallery .lightbox:before {
      top: 50%;
      left: 50%;
      margin-top: -13px;
      margin-left: -13px;
      opacity: 0;
      color: #fff;
      font-size: 26px;
      font-family: 'Glyphicons Halflings';
      content: '\e003';
      pointer-events: none;
      z-index: 9000;
      transition: 0.4s;
  }


  .tz-gallery .lightbox:after {
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      opacity: 0;
      background-color: rgba(46, 132, 206, 0.7);
      content: '';
      transition: 0.4s;
  }

  .tz-gallery .lightbox:hover:after,
  .tz-gallery .lightbox:hover:before {
      opacity: 1;
  }

  .baguetteBox-button {
      background-color: transparent !important;
  }

  @media(max-width: 768px) {
      body {
          padding: 0;
      }
  }
</style>
<div class="container gallery-container">

    <h1>Artworks Gallery</h1>

    <p class="page-description text-center">Find all the beautiful artworks and pieces from our various artists</p>

    <div class="tz-gallery">
    <% if current_user %>
        <%= link_to "New artwork", new_artwork_path, class: "btn btn-outline-secondary" %>
    <% end %>
        <div class="row">
          <% @artworks.each do |artwork| %>
            <% artwork.images.each do |image| %>
            <div class="col-sm-12 col-md-4">
              <%= link_to url_for(image), data: { lightbox: "artwork-group", title: artwork.description } do %>
                <%= image_tag url_for(image), alt: artwork.description, class: "img-thumbnail" %>
              <% end %>
            </div>
            <% end %>
          <% end %>
        </div>

    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>

<script>
    baguetteBox.run('.tz-gallery');
</script>

app/views/artworks/new.html.erb
<% content_for :title, "New artwork" %>

<h1>New artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artwork %>

<div>
  <%= link_to "Back to artworks", artworks_path %>
  <% if current_user&.admin %>
    <%= link_to "Edit this artwork", edit_artwork_path(@artwork) %> |

    <%= button_to "Destroy this artwork", @artwork, method: :delete %>
  <% end %>
</div>